name: Build and Publish

on:
  push:
    branches:
      - main

env:
  MAVEN_USERNAME: ${{ secrets.CI_MAVEN_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.CI_MAVEN_PASSWORD }}
  SIGNING_KEY_ID: ${{ secrets.CI_SIGNING_KEY_ID }}
  SIGNING_PASSWORD: ${{ secrets.CI_SIGNING_PASSWORD }}
  SIGNING_KEY: ${{ secrets.CI_SIGNING_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      - name: Build
        run: |
          cp secret.properties.sample secret.properties
          gradle build

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      - name: Publish to Maven repository
        run: |
          echo "ossrhUsername=$MAVEN_USERNAME" >> secret.properties
          echo "ossrhPassword=$MAVEN_PASSWORD" >> secret.properties
          echo "signing.keyId=$SIGNING_KEY_ID" >> secret.properties
          echo "signing.password=$SIGNING_PASSWORD" >> secret.properties
          echo "signing.secretKey=$SIGNING_KEY" >> secret.properties
          gradle publishJvmPublicationToMavenRepository
